title: Stacy Shelley
google_analytics: G-C5WWE06MNN
description: Cybersecurity Marketing Leader
url: "https://stacyshelley.com"
baseurl: ""

permalink: /:year/:month/:day/:title/

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .github